--
-- PostgreSQL database dump
--

-- Dumped from database version 13.1
-- Dumped by pg_dump version 13.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: course; Type: TABLE; Schema: public; Owner: yoichi2
--

CREATE TABLE public.course (
    id integer NOT NULL,
    name character varying(120) NOT NULL,
    state character varying(120),
    image_link character varying(500)
);


ALTER TABLE public.course OWNER TO yoichi2;

--
-- Name: course_id_seq; Type: SEQUENCE; Schema: public; Owner: yoichi2
--

CREATE SEQUENCE public.course_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.course_id_seq OWNER TO yoichi2;

--
-- Name: course_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: yoichi2
--

ALTER SEQUENCE public.course_id_seq OWNED BY public.course.id;


--
-- Name: drink; Type: TABLE; Schema: public; Owner: yoichi2
--

CREATE TABLE public.drink (
    id integer NOT NULL,
    title character varying(100),
    recipe character varying(180) NOT NULL
);


ALTER TABLE public.drink OWNER TO yoichi2;

--
-- Name: drink_id_seq; Type: SEQUENCE; Schema: public; Owner: yoichi2
--

CREATE SEQUENCE public.drink_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.drink_id_seq OWNER TO yoichi2;

--
-- Name: drink_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: yoichi2
--

ALTER SEQUENCE public.drink_id_seq OWNED BY public.drink.id;


--
-- Name: persons; Type: TABLE; Schema: public; Owner: yoichi2
--

CREATE TABLE public.persons (
    id integer NOT NULL,
    user_id character varying,
    name character varying(30) NOT NULL
);


ALTER TABLE public.persons OWNER TO yoichi2;

--
-- Name: persons_id_seq; Type: SEQUENCE; Schema: public; Owner: yoichi2
--

CREATE SEQUENCE public.persons_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.persons_id_seq OWNER TO yoichi2;

--
-- Name: persons_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: yoichi2
--

ALTER SEQUENCE public.persons_id_seq OWNED BY public.persons.id;


--
-- Name: player; Type: TABLE; Schema: public; Owner: yoichi2
--

CREATE TABLE public.player (
    id integer NOT NULL,
    name character varying NOT NULL,
    user_id character varying,
    image_link character varying(500)
);


ALTER TABLE public.player OWNER TO yoichi2;

--
-- Name: player_id_seq; Type: SEQUENCE; Schema: public; Owner: yoichi2
--

CREATE SEQUENCE public.player_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.player_id_seq OWNER TO yoichi2;

--
-- Name: player_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: yoichi2
--

ALTER SEQUENCE public.player_id_seq OWNED BY public.player.id;


--
-- Name: score; Type: TABLE; Schema: public; Owner: yoichi2
--

CREATE TABLE public.score (
    id integer NOT NULL,
    player_id integer,
    course_id integer,
    score integer NOT NULL,
    date character varying
);


ALTER TABLE public.score OWNER TO yoichi2;

--
-- Name: score_id_seq; Type: SEQUENCE; Schema: public; Owner: yoichi2
--

CREATE SEQUENCE public.score_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.score_id_seq OWNER TO yoichi2;

--
-- Name: score_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: yoichi2
--

ALTER SEQUENCE public.score_id_seq OWNED BY public.score.id;


--
-- Name: course id; Type: DEFAULT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.course ALTER COLUMN id SET DEFAULT nextval('public.course_id_seq'::regclass);


--
-- Name: drink id; Type: DEFAULT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.drink ALTER COLUMN id SET DEFAULT nextval('public.drink_id_seq'::regclass);


--
-- Name: persons id; Type: DEFAULT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.persons ALTER COLUMN id SET DEFAULT nextval('public.persons_id_seq'::regclass);


--
-- Name: player id; Type: DEFAULT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.player ALTER COLUMN id SET DEFAULT nextval('public.player_id_seq'::regclass);


--
-- Name: score id; Type: DEFAULT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.score ALTER COLUMN id SET DEFAULT nextval('public.score_id_seq'::regclass);


--
-- Data for Name: course; Type: TABLE DATA; Schema: public; Owner: yoichi2
--

COPY public.course (id, name, state, image_link) FROM stdin;
1	Narita	Chiba	www1
2	HakoneCC	Kanagawa	www2
\.


--
-- Data for Name: drink; Type: TABLE DATA; Schema: public; Owner: yoichi2
--

COPY public.drink (id, title, recipe) FROM stdin;
\.


--
-- Data for Name: persons; Type: TABLE DATA; Schema: public; Owner: yoichi2
--

COPY public.persons (id, user_id, name) FROM stdin;
\.


--
-- Data for Name: player; Type: TABLE DATA; Schema: public; Owner: yoichi2
--

COPY public.player (id, name, user_id, image_link) FROM stdin;
1	player1	auth0|6056a19f618f4a00718103c2	\N
6	test_player5	auth0_test	www1
\.


--
-- Data for Name: score; Type: TABLE DATA; Schema: public; Owner: yoichi2
--

COPY public.score (id, player_id, course_id, score, date) FROM stdin;
7	1	2	90	20210331
3	1	1	90	\N
10	6	1	110	20210210
11	6	2	120	20210205
\.


--
-- Name: course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yoichi2
--

SELECT pg_catalog.setval('public.course_id_seq', 4, true);


--
-- Name: drink_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yoichi2
--

SELECT pg_catalog.setval('public.drink_id_seq', 1, false);


--
-- Name: persons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yoichi2
--

SELECT pg_catalog.setval('public.persons_id_seq', 1, false);


--
-- Name: player_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yoichi2
--

SELECT pg_catalog.setval('public.player_id_seq', 6, true);


--
-- Name: score_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yoichi2
--

SELECT pg_catalog.setval('public.score_id_seq', 11, true);


--
-- Name: course course_name_key; Type: CONSTRAINT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_name_key UNIQUE (name);


--
-- Name: course course_pkey; Type: CONSTRAINT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);


--
-- Name: drink drink_pkey; Type: CONSTRAINT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.drink
    ADD CONSTRAINT drink_pkey PRIMARY KEY (id);


--
-- Name: drink drink_title_key; Type: CONSTRAINT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.drink
    ADD CONSTRAINT drink_title_key UNIQUE (title);


--
-- Name: persons persons_pkey; Type: CONSTRAINT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT persons_pkey PRIMARY KEY (id);


--
-- Name: player player_name_key; Type: CONSTRAINT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_name_key UNIQUE (name);


--
-- Name: player player_pkey; Type: CONSTRAINT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_pkey PRIMARY KEY (id);


--
-- Name: score score_pkey; Type: CONSTRAINT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.score
    ADD CONSTRAINT score_pkey PRIMARY KEY (id);


--
-- Name: score score_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.score
    ADD CONSTRAINT score_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- Name: score score_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: yoichi2
--

ALTER TABLE ONLY public.score
    ADD CONSTRAINT score_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- PostgreSQL database dump complete
--

